const vocations=[['knight','Elite Knight','EK','⚔'],['paladin','Royal Paladin','RP','➳'],['sorcerer','Master Sorcerer','MS','✦'],['druid','Elder Druid','ED','❈'],['monk','Exalted Monk','EM','◉']];
const vocationBase={knight:{hp:15,mana:5,dmg:1.08,mit:16.8},paladin:{hp:10,mana:15,dmg:1.04,mit:10.5},sorcerer:{hp:5,mana:30,dmg:1.14,mit:6.2},druid:{hp:5,mana:30,dmg:1.10,mit:7.1},monk:{hp:10,mana:20,dmg:1.07,mit:12.4}};
const slots=[['weapon','Arma','⚔'],['helmet','Casco','♜'],['amulet','Amuleto','◇'],['shield','Escudo','◈'],['armor','Armadura','♟'],['ring','Anillo','○'],['boots','Botas','∪'],['legs','Piernas','♙'],['quiver','Extra','▣']];
const items={weapon:[['Sanguine Blade',8,14],['Soulshredder',6,12],['Falcon Longsword',3,8]],helmet:[['Spiritthorn Helmet',2,5],['Cobra Hood',1,4],['Terra Helmet',0,3]],amulet:[['Werewolf Amulet',0,6],['Lion Amulet',0,5]],shield:[['Spiritthorn Shield',0,9],['Falcon Escutcheon',0,7]],armor:[['Spiritthorn Armor',4,12],['Lion Plate',3,9]],ring:[['Prismatic Ring',0,8],['Axe Ring',4,0]],boots:[['Soulwalkers',1,5],['Depth Calcei',0,4]],legs:[['Fabulous Legs',2,7],['Falcon Greaves',3,9]],quiver:[['Moon Mirror',0,3],['Sun Catcher',0,3]]};
const spellPool=[['Exori Gran','Berserk','Physical',2250,'✹'],['Exori Mas','Groundshaker','Physical',1480,'◌'],['Exori','Brutal Strike','Physical',1720,'✦'],['Exori Min','Front Sweep','Physical',980,'⌁'],['Exori Gran Ico','Fierce Berserk','Physical',1416,'✧'],['Utito Tempo','Blood Rage','Buff',0,'↑'],['Exeta Res','Challenge','Utility',0,'◎']];
const state={vocation:'knight',slot:'weapon',equipment:{},domains:[120,100,100,100],rotation:[0,1,2,3,4],logged:false};

function el(id){return document.getElementById(id)}
function fmt(n){return Math.round(n).toLocaleString('es-CO')}
function toast(msg){const t=el('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function renderVocations(){el('vocations').innerHTML=vocations.map(v=>`<div class="vocation ${state.vocation===v[0]?'active':''}" data-voc="${v[0]}"><div class="voc-icon">${v[3]}</div><b>${v[1]}</b><small>${v[2]}</small></div>`).join('');document.querySelectorAll('.vocation').forEach(x=>x.onclick=()=>{state.vocation=x.dataset.voc;renderVocations();calculate()})}
function renderEquipment(){el('paperdoll').innerHTML=slots.map((s,i)=>`<button class="slot ${state.slot===s[0]?'active':''}" data-slot="${s[0]}" style="${i===0?'grid-row:2':''}"><span class="slot-icon">${s[2]}</span><small>${state.equipment[s[0]]?.name||s[1]}</small></button>`).join('');document.querySelectorAll('.slot').forEach(x=>x.onclick=()=>{state.slot=x.dataset.slot;renderEquipment();renderItemEditor()});renderItemEditor()}
function renderItemEditor(){const s=slots.find(x=>x[0]===state.slot);el('slotTitle').textContent=s[1];const list=items[state.slot];el('itemSelect').innerHTML=list.map((x,i)=>`<option value="${i}">${x[0]}</option>`).join('');const current=state.equipment[state.slot]||{name:list[0][0],skill:list[0][1],armor:list[0][2],idx:0};el('itemSelect').value=current.idx||0;el('itemStats').innerHTML=`<b>${current.name}</b><br>Skill: +${current.skill} · Protección: +${current.armor}`;el('itemSelect').onchange=e=>{const x=list[+e.target.value];state.equipment[state.slot]={name:x[0],skill:x[1],armor:x[2],idx:+e.target.value};renderEquipment();calculate()}}
function renderDomains(){const names=[['Furia','Daño físico'],['Fortaleza','HP y mitigación'],['Maestría','Skill y crítico'],['Disciplina','Mana y sustain']];el('domains').innerHTML=names.map((n,i)=>`<div class="domain"><div class="domain-head"><b>${n[0]}</b><span>${n[1]}</span></div><div class="domain-control"><input type="range" min="0" max="180" step="10" value="${state.domains[i]}" data-domain="${i}"><output>${state.domains[i]}</output></div></div>`).join('');document.querySelectorAll('[data-domain]').forEach(x=>x.oninput=()=>{state.domains[+x.dataset.domain]=+x.value;renderDomains();calculate()})}
function renderProf(){const perks=['Impacto +3%','Skill +2','Crítico +2%','Leech +3%','Impacto +5%','Maestría'];el('proficiencyTrack').innerHTML=perks.map((p,i)=>`<div class="prof-level"><div class="prof-node">${i+1}</div><select><option>${p}</option><option>Defensa +${i+2}%</option><option>Mana +${(i+1)*2}%</option></select></div>`).join('')}
function renderRotation(){el('rotationList').innerHTML=state.rotation.map((idx,i)=>{const s=spellPool[idx];return `<div class="spell"><span class="spell-num">${String(i+1).padStart(2,'0')}</span><span class="spell-icon">${s[4]}</span><div><b>${s[0]}</b><small>${s[1]} · ${s[2]}</small></div><b class="spell-dmg">${s[3]?fmt(s[3]):'BUFF'}</b><button class="remove-spell" data-remove="${i}">×</button></div>`}).join('');document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{state.rotation.splice(+x.dataset.remove,1);renderRotation();calculate()});el('rotationStep').textContent=`${state.rotation.length} hechizos`}
function calculate(){const level=+el('level').value||500,skill=+el('skill').value||100,magic=+el('magic').value||0,base=vocationBase[state.vocation];const equip=Object.values(state.equipment);const eqSkill=equip.reduce((a,x)=>a+(x.skill||0),0),armor=equip.reduce((a,x)=>a+(x.armor||0),0);const points=state.domains.reduce((a,b)=>a+b,0);const fury=state.domains[0]/1000,mastery=state.domains[2]/1500;const rotationBase=state.rotation.reduce((a,i)=>a+spellPool[i][3],0);const skillScale=.68+skill/350;const damage=rotationBase*skillScale*base.dmg*(1+fury+mastery+eqSkill/400);const crit=10+(el('imbue').value==='crit'?10:0)+Math.floor(state.domains[2]/60);const hp=185+level*base.hp+state.domains[1]*2;const mana=50+level*base.mana+state.domains[3]*2;const mit=base.mit+armor/15+state.domains[1]/100;const voc=vocations.find(x=>x[0]===state.vocation);el('summaryVocation').innerHTML=`${voc[1]} <span>• Nv. ${level}</span>`;el('cycleDamage').textContent=fmt(damage);el('dps').textContent=fmt(damage/Math.max(2,state.rotation.length*.8));el('critChance').textContent=crit+'%';el('hp').textContent=fmt(hp);el('mana').textContent=fmt(mana);el('skillOut').textContent=skill+eqSkill;el('mitigation').textContent=mit.toFixed(1)+'%';el('score').textContent=fmt(damage*.72+hp*.22+mit*80+magic*20);el('scoreDelta').textContent=`+${(fury*100+mastery*100).toFixed(1)}% vs. base`;el('wheelTotal').textContent=points;el('wheelAvailable').textContent=(Math.max(0,level-50-points))+' DISPONIBLES';el('wheelStep').textContent=`${points} / ${Math.max(0,level-50)} puntos`;el('saveStatus').textContent='Cambios sin guardar'}
function save(publicBuild=false){const data={name:el('buildName').value,...state,level:el('level').value,skill:el('skill').value,magic:el('magic').value,public:publicBuild};localStorage.setItem('forge-build',JSON.stringify(data));el('saveStatus').textContent=publicBuild?'Build pública':'Guardado ahora';toast(publicBuild?'Build publicada en modo demo':'Build guardada en este dispositivo')}
function load(){try{const d=JSON.parse(localStorage.getItem('forge-build'));if(!d)return;Object.assign(state,d);el('buildName').value=d.name;el('level').value=d.level;el('skill').value=d.skill;el('magic').value=d.magic}catch(e){}}
document.querySelectorAll('.step').forEach(b=>b.onclick=()=>{document.querySelectorAll('.step,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');el(b.dataset.panel).classList.add('active')});['level','skill','magic','scenario','imbue'].forEach(id=>el(id).oninput=calculate);el('addSpell').onclick=()=>{state.rotation.push(state.rotation.length%spellPool.length);renderRotation();calculate()};
el('saveBtn').onclick=()=>save(false);el('publishBtn').onclick=()=>state.logged?save(true):(el('authModal').showModal(),toast('Inicia sesión para publicar'));el('loginBtn').onclick=()=>el('authModal').showModal();document.querySelector('.close-modal').onclick=()=>el('authModal').close();el('mockLogin').onclick=()=>{state.logged=true;el('loginBtn').textContent='Mi perfil';el('authModal').close();toast('Sesión de demostración iniciada')};
el('buildCards').innerHTML=[['Elite Knight','La muralla de Roshamuul','AresK','9.2k'],['Royal Paladin','Santuario: daño y sustain','Lunara','8.8k'],['Elder Druid','Sanación de dúo — Ice Library','Nym','8.4k']].map(x=>`<article class="build-card"><span class="tag">${x[0].toUpperCase()} · DESTACADA</span><h3>${x[1]}</h3><p>Build equilibrada para cacería prolongada, con rotación y equipo optimizados.</p><div class="card-meta"><span>por ${x[2]}</span><span>♢ ${x[3]} poder</span></div></article>`).join('');
slots.forEach(s=>{const x=items[s[0]][0];state.equipment[s[0]]={name:x[0],skill:x[1],armor:x[2],idx:0}});load();renderVocations();renderEquipment();renderDomains();renderProf();renderRotation();calculate();
